stages:
  - lint
  - test
  - build
  - extension_tests
  - deploy

cache:
  paths:
    - node_modules

before_script:
  - test ! -z "$CI_NPM_REGISTRY" && npm config set registry $CI_NPM_REGISTRY || true
  - unset HTTP_PROXY
  - unset ALL_PROXY
  - npm install
  # ssh key
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo -n $GITLAB_KEY > ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

copyright_lint_test:
  image: electronuserland/builder:11
  stage: lint
  tags:
    - lint_brno
  before_script:
    - echo "Skipping before_script"
  script:
    - cd ci && python copyright_header_checker.py -d ../src ../menuconfig -x ../menuconfig/js/lib ../src/views ../src/views/menuconfig  -e js ts py

typescript_lint_test:
  image: electronuserland/builder:11
  stage: lint
  tags:
    - lint_brno
  script:
    - npm run tslint

javascript_lint_test:
  image: electronuserland/builder:11
  stage: lint
  tags:
    - lint_brno
  script:
    - npm run eslint

npm_vulnerabilities_test:
  image: electronuserland/builder:11
  stage: lint
  tags:
    - brno_build
  script:
    - npm audit --registry=https://registry.npmjs.org

python_lint_test:
  image: $CI_DOCKER_REGISTRY/ubuntu-test-env
  stage: lint
  tags:
    - lint_brno
  artifacts:
    when: on_failure
    paths:
      - flake8_output.txt
      - bandit_output.txt
    expire_in: 1 week
  before_script:
    - source /opt/pyenv/activate
    - pyenv global 2.7.15
    - python -m pip install bandit flake8
  script:
    - python -m bandit -r -f txt -o bandit_output.txt .
    - python -m flake8 --config=.flake8 --output-file=flake8_output.txt --tee

build_tar:
  image: electronuserland/builder:11
  stage: build
  tags:
    - brno_build
  artifacts:
    paths:
      - espressif-esp-idf-extension-*.tar.gz
  script:
    - PACKAGE_VERSION=$(node -p "require('./package.json').version")
    - cd ..
    - tar -pczf espressif-esp-idf-extension-$PACKAGE_VERSION.tar.gz $CI_PROJECT_NAME --exclude "$CI_PROJECT_NAME/node_modules" --exclude "$CI_PROJECT_NAME/.git"
    - mv espressif-esp-idf-extension-$PACKAGE_VERSION.tar.gz $CI_PROJECT_NAME
    - cd $CI_PROJECT_NAME

build_vsix:
  image: electronuserland/builder:11
  stage: build
  tags:
    - brno_build
  artifacts:
    paths:
      - esp-idf-extension-*.vsix
  script:
    - npm add vsce
    - npm add gulp
    - ./node_modules/.bin/gulp build
    - VERSION_STR=${CI_COMMIT_TAG:-g${CI_COMMIT_SHA:0:8}}
    - ./node_modules/.bin/vsce package -o esp-idf-extension-${VERSION_STR}.vsix

deploy_github:
  stage: deploy
  tags:
    - deploy
  before_script:
    - echo "Skipping before_script"
  script:
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo -n $GH_PUSH_KEY > ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - git remote remove github &>/dev/null || true
    - git remote add github git@github.com:espressif/${VSCODE_ESP_IDF_REPO}.git
    - cd ci && ./push_to_github.sh
  when: manual

tests_extension_units:
  image: $CI_DOCKER_REGISTRY/ubuntu-vscode:1-f5756a91
  stage: extension_tests
  tags:
    - brno_build
  artifacts:
    paths:
    - "*.log"
    reports:
      junit:
        - results/*
    when: always
    expire_in: 1 week
  script:
    - rm /tmp/.X99-lock
    - Xvfb :99 & sleep 2

    - xdpyinfo -display :99
    - export DISPLAY=":99"

    - cd /builds/idf/vscode-plugin

    - sudo apt-get update
    - sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -q python-pip net-tools
    - npm run compile --loglevel verbose
    - chmod -R 777 ./node_modules/vscode/bin
    - export CODE_TESTS_PATH="/builds/idf/vscode-plugin/out/test" & sleep 5
    - /builds/idf/vscode-plugin/node_modules/vscode/bin/test --user-data-dir='./.Code' --VERBOSE >> testing.results.log
